[tools]

neovim = "latest"
ripgrep = "latest"
lsd = "latest"
bat = "latest"
fzf = "latest"
fd = "latest"
node = "latest"
chezmoi = "latest"
starship = "latest"
lazygit = "latest"
usage = "latest"
tmux = "latest"
