format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$python\
$nodejs\
$haskell\
$elixir\
$ocaml\
$lua\
$cpp\
$rust\
$container\
$kubernetes\
$line_break\
$character\
"""

[fill]
symbol = " "

[directory]
style = "green"
read_only = "󰌾"
# truncation_length = 4
truncate_to_repo = false

[container]
symbol = "󰡨 "
style = "bold blue dimmed"
format = '[$symbol $name]($style) '

[character]
success_symbol = '[ 󰘧 ](bold green)'
error_symbol = '[󰘧 ](red)'
vimcmd_symbol = '[❮󰘧 ](yellow)'

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = " "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[aws]
symbol = " "
style = "bold yellow"

[kubernetes]
format = '[ $context  \($namespace\) ](bold green) '
symbol = " "
style = "bold green"
disabled = false

[rust]
format = '[$symbol($version )]($style)'
symbol = " "
style = "bold red"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = '[$symbol($version )]($style)'
symbol = " "
style = "bold yellow"

[haskell]
format = '[$symbol($version )]($style)'
symbol = " "

[elixir]
symbol = " "
style = "bold purple"

[ocaml]
symbol = " "
style = "bold yellow"

[lua]
symbol = " "
style = "bold purple"

[cpp]
symbol = " "
style = "bold blue"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
